# Generated by Django 4.0.5 on 2023-07-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculomodel',
            options={'permissions': (('visualizar_catalogo', 'Puede visualizar_catalogo'),)},
        ),
        migrations.AlterField(
            model_name='vehiculomodel',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
